### ISSUE TITLE
Prompt (or equivalent) implementation example?

### ISSUE THREAD

**Issue by tonydero** [willmcgugan/textual#100]
So far I'm loving working with this library. I see a lot of promise!

I'm working on creating a very simple app right now, using the `simple.py` example as a starting point, but I needed to capture input from the user. I tried creating a new Widget using a rich `Prompt` object and putting it in the sidebar, but when it runs the prompt just shows up at the bottom with nothing else, and I am unable to interact with it at all (actually have to kill the whole terminal, but that's probably just due to poor error handling on my part). Is there something I'm not doing right for this to work, or is this just a yet-to-be-implemented functionality ? Full simple test class:

```py
class TestInput(Widget):
    def render(self) -> Prompt:
        test_val = Prompt.ask('Enter Val')
        return test_val
```

Thanks for any assistance!

**Comment by willmcgugan** [comment]
Prompt uses `input()` under the hood, which blocks, so won't work in Textual I'm afraid. Textual doesn't have any text input widget (yet), but I there is a third part library for it (https://github.com/sirfuzzalot/textual-inputs), which I have yet to have a look at.
