### ISSUE TITLE
Hangs on Esc key press

### ISSUE THREAD

**Issue by gmagno** [willmcgugan/textual#114]
Hey, another hang similar to #13. Follows a video:

https://user-images.githubusercontent.com/46817915/134103761-33988da2-f71a-41e2-9ab0-8e927ceb47a9.mp4

**Comment by Lunchmeat8** [comment]
They were watching my shit damn it thanks...

**Comment by willmcgugan** [comment]
Thanks. I can reproduce that.

**Comment by willmcgugan** [comment]
SHould be fixed in 0.1.13
