### ISSUE TITLE
User path inside DirectoryTree widget (also is an entry-point).

### ISSUE THREAD

**Issue by UriyaHarpeness** [willmcgugan/textual#120]
Here are the last lines in the file https://github.com/willmcgugan/textual/blob/main/src/textual/widgets/_directory_tree.py#L133:
```
if __name__ == "__main__":
    from textual import events
    from textual.app import App

    class TreeApp(App):
        async def on_mount(self, event: events.Mount) -> None:
            await self.view.dock(DirectoryTree("/Users/willmcgugan/projects"))

    TreeApp.run(log="textual.log")
```

I assume this behavior is not wanted.

**Comment by tusharsadhwani** [comment]
I suppose the actual example can use "." as the path, or maybe `Path(__file__).parent()`

**Comment by willmcgugan** [comment]
It's just test code, you can ignore it. It will likely evolve in to an example before v1.0.
