### ISSUE TITLE
Better support for inputs and multiple classes.

### ISSUE THREAD

**Issue by ZeroIntensity** [willmcgugan/textual#193]
textual doesn't have a very good way of getting input as of now. the only way to do it is by using an `on_key` event and testing for the enter key to end the input. while this works, it ends up getting very limited and being a headache to work with (especially with async).

for example, we have 2 classes, and one needs to get input:

```py
class MyApp(App):
    async def on_load(self, event: events.Load) -> None:
        self.text = ""
        self.some_class: Optional["SomeClass"]

    async def on_key(self, event: events.Key) -> None:
        key: str = event.key

        if key == "enter":
            await self.some_class.finish_input(self.text)
        self.text += key

class SomeClass:
    def start(self) -> None:
        self.app = MyApp()
        self.app.run() # thread is blocked here, so we dont even get to the code below

        self.app.some_class = self
        ... # some other stuff here

    async def finish_input(self, text: str) -> None:
        ... # do something with the text
        await send_to_some_other_function(text)
```
since textual blocks the thread with `run()`, theres not a very good way to send things down to another class (at least when the textual app isn't the main class).
even if we could, trying to synchronize the app and the function waiting for the input would be practically impossible. 

something i've also noticed while working with textual, is that it's a pain to work with when the app isn't the main class or being called from other async functions.

for example, when we have a class that starts textual on its own from an async function, a `RuntimeError` is generated by asyncio

```py
class Client:
    async def start(self) -> None:
        ... # some other async stuff
        MyApp.run() # this generates an error due to run() creating a new event loop
```

when the textual class isn't being run from the main thread, you cannot start it at all with `run()`.
however, there is a workaround to this, which is to await `App.process_messages()`, but this still blocks the thread so it would be pretty much pointless.

please implement better support for both of these.

**Comment by willmcgugan** [comment]
I see you're 13, and clearly very smart to be coding at this level, but its best not to make assertions about how the API works when you're asking the guy who wrote it.

Regarding key events. It's not just the App that can receive them. If you call the `focus()` method on a custom widget, it will receive key events also. If you are implementing a widget, this is probably what you should do.

Your second "question" may be moot if you follow the advice above, but it isn't a Textual issue. If you want to run something else in parallel  with Textual, you can launch a task, which may be awaited. If you want that task to be able to respond to input, you will need to implement some way of communicating the key with that task. Textual uses a queue to do this, you could implement something similar.

Hope that helps.

**Comment by ZeroIntensity** [comment]
ah, thought i was missing something. thank you
