### ISSUE TITLE
Textual In Browser?

### ISSUE THREAD

**Issue by carsonharmon** [willmcgugan/textual#53]
Hi Will, 

I love the TUI aesthetic and wanted to make a personal website for myself based on something like xterm.js. 

I saw your AMA on Reddit about textual, and since it has more in common with JS frameworks, I was wondering if there was a way to display the TUI's in a browser? 

Thanks for your time and for your open source work.

**Comment by lllama** [comment]
So I'm pretty sure I've seen Textual running in the terminal in VS Code, and that uses xterm.js so there's no reason it won't work in the browser.

**Comment by willmcgugan** [comment]
THere's no build in way at the moment, but I'm sure any terminal in a browser solution will work just fine.

**Comment by lllama** [comment]
I've used this before to host a bash prompt on a website: https://tsl0922.github.io/ttyd/

I'm sure you could point it at A Textual app.

**Comment by eudoxos** [comment]
For the record, `ttyd` works nicely (`ttyd -p 9090  python3 -m textual.app`), it also handles multiple clients gracefully — each new client gets its own instance of the app.

It is not visually perfect, though it might be perhaps improved by specifying custom font via ttyd theming params (`-t`; https://github.com/tsl0922/ttyd/issues/31 discusses custom fonts).

![image](https://user-images.githubusercontent.com/1029876/181209413-a09bb6f2-bf35-46ac-8eea-453d92c24102.png)
