### ISSUE TITLE
Typing error with Reactive

### ISSUE THREAD

**Issue by abey79** [willmcgugan/textual#55]
PyCharm gives me typing error with Reactive, see screenshot:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/49431240/129097352-b2e08dbf-c876-409c-8f8c-31834aab1430.png">

I'm unsure why this is the case given that mypy doesn't yield such error.

Side question: now that I have found myself a project to use Textual while fully understanding that this is WIP, I'll likely come across many little things like this one you may already be aware of. Should I keep opening issues? Or should I use some other, less formal avenue to keep the noise low and only open ticket when you request it? I'm thinking of Twitter DMs, or possibly some discord server and/or DM. Let me know what works best for you at this stage.

**Comment by cmckain** [comment]
PyCharm's support for non-standard or non-class types has been a problem for a while (see https://youtrack.jetbrains.com/issue/PY-27627) but, to stop the annoying warnings, I just changed the type of Reactive objects to 'Reactive[str] | str' (or 'Union[Reactive[str], str]' for those who aren't crazy enough to use 3.10). That technically happens because "BAXI" isn't typed as Reactive[str] but as str.

**Comment by kkanekii** [comment]
what's that font bro 0_0 it looks sick

**Comment by abey79** [comment]
@willmcgugan Indeed mypy is fine. As @cmckain suggests, this is probably a PyCharm issue (it uses its own analyser it seems). I'm not sure if there is something that could be done about it on Textual side.

@cmckain Just so I understand it right, you made that change in Textual source? I'll probably just disable the PyCharm warning for those lines when/if that project becomes serious enough for my "green mark" OCD to take over.

@kkanekii if you are referring to my screenshot, this is JetBrains Mono, which JetBrains made for their IDEs. I do like it indeed.

**Comment by cmckain** [comment]
@abey79 No, just on the variables listed when the subclassed class is created. If the Reactive type does sometimes special, you could always make it so every interaction with the variables in question is done via the Reactive function (so no normal str or ints would be there to cause the warning).

**Comment by willmcgugan** [comment]
To be honest, I think you're better off ignore those errors with "type: ignore" or equivalent. The PyCharm tooling is in error here, and by the looks of it they might fix it soon enough.

**Comment by abey79** [comment]
Indeed.
