### ISSUE TITLE
`NoneType in await` and many more problems with example code

### ISSUE THREAD

**Issue by octoshrimpy** [willmcgugan/textual#66]
Latest update broke something :sweat_smile: 

work machine: 3.7.x, `pip install rich, textual, pyfiglet`
home machine: 3.7.10, 3.9.6, `pip install rich, textual, pyfiglet`

Downloaded yesterday, everything works fine (work machine, don't have access at the moment, will update this tomorrow), downloaded again tonight on personal machine and I cannot get example code to run. constant `expects 1 argument but 2 were given` across almost all examples, including the base Beeper app, and the background color switcher spits out `object NoneType can't be used in 'await' expression`. I know rich is still working, because the output is colored: 
![image](https://user-images.githubusercontent.com/7097172/129837010-1862f74a-0ee5-482e-827e-04679d8a2b7b.png)

I pulled the code and built myself with `poetry install` and used that for the examples (I think I did it correctly) and still no-go.

**Comment by willmcgugan** [comment]
Hi @octoshrimpy Can you double check you have the repo version installed. You may need to do `pip uninstall textual` prior to doing `poetry install`.

**Comment by willmcgugan** [comment]
Closing this, reopen if it doesn't solve the problem

**Comment by octoshrimpy** [comment]
Does it need to be installed within the project folder? I'm new to manually installed dependencies on python. After uninstalling through pip and running poetry install (successfully), the code now complains about missing textual dep. 

```
projects
    textual
        src
        ...
    current_project
        main.py
```

That is my current folder structure.

**Comment by tusharsadhwani** [comment]
@octoshrimpy textual doesn't need to be cloned at all. you just need to add textual as a dependency in your `pyproject.toml` file, or do `pip install textual` inside the current project's virtualenvironment. To learn more about virtualenvironments, check [here](https://virtualenv.pypa.io/en/latest/user_guide.html)
