### ISSUE TITLE
error when running examples

### ISSUE THREAD

**Issue by itsUrcute** [willmcgugan/textual#71]
i installed textual with pip and i tried to run the first example in the readme with `python3 filename.py` but i get the error `TypeError: on_key() takes 1 positional argument but 2 were given` when i press a key. got a similiar error with another example. sorry if im being dumb : p

**Comment by willmcgugan** [comment]
You will need to install via poetry. Do 'pip uninstall textual' then 'poetry install' before running the examples...

**Comment by itsUrcute** [comment]
sorry im kinda new to python so i may be messing something up. i did `python3 -m poetry add textual` and now its telling me textual isnt a module. the `pyproject.toml` file and `poetry.lock` file both add up though

the error is
```py
from textual.app import App
ModuleNotFoundError: No module named 'textual'
```

**Comment by itsUrcute** [comment]
so i did `poetry run python filename.py` and got the initial error `TypeError: on_key() takes 1 positional argument but 2 were given`. would appreciate some help on this

**Comment by cole-wilson** [comment]
I am also having trouble with this exact same error. Running `python3 -m textual.app` runs the demo just fine, but running the examples failed. I have installed everything with poetry.

**Comment by prolomix** [comment]
Please help I did what you said but Visual Studio tells me " There is no module called 'textual'."
then I uninstall 'textual' and Now cd into the textual directory and run the following: poetry installs and cmd pop up with an error.
![tempsnip](https://user-images.githubusercontent.com/89859834/131635543-5758a421-2178-4b5e-9a40-506f228f9774.png)

# #

**Comment by willmcgugan** [comment]
@cole-wilson You can use the version on PyPi just by adding textual to your project. These instructions are so you can try out the latest code before it is released.

@prolomix You will need to get the latest code from the repository (here). You can do this by *cloning* the repos. Click the code tab above and then the green Code button.

<img width="1266" alt="Screen Shot 2021-09-01 at 09 11 42" src="https://user-images.githubusercontent.com/554369/131636435-7b74aef7-d8a2-45e8-9b65-9d1db6843e51.png">

If you have never done this before, see if you can find a guide online.

**Comment by prolomix** [comment]
@willmcgugan Ok I will do it

**Comment by prolomix** [comment]
I did it and it shows the same
but i run test file and it showed me this:
![Untitled](https://user-images.githubusercontent.com/89859834/131642743-dac3d6c9-9dd9-4dee-81f3-8933d1a2b4db.png)

**Comment by prolomix** [comment]
> I did it and it shows the same
> but I run test file and it showed me this:
> ![Untitled](https://user-images.githubusercontent.com/89859834/131642743-dac3d6c9-9dd9-4dee-81f3-8933d1a2b4db.png)

what does this mean

**Comment by willmcgugan** [comment]
Ah. You are running on Windows. Textual is not yet compatible with Windows I'm afraid.

**Comment by prolomix** [comment]
Ok @willmcgugan

**Comment by prolomix** [comment]
When it will be available for windows

**Comment by willmcgugan** [comment]
Can't say for certain, but I would suspect a month or two.

**Comment by cole-wilson** [comment]
@willmcgugan thanks!
