### ISSUE TITLE
Add more easing functions

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/textual#81]
There are a number of 'easing functions' used by the animation system. At the top of _animator.py you will see the following:

```python
EASING = {
    "none": lambda x: 1.0,
    "round": lambda x: 0.0 if x < 0.5 else 1.0,
    "linear": lambda x: x,
    "in_cubic": lambda x: x * x * x,
    "in_out_cubic": lambda x: 4 * x * x * x if x < 0.5 else 1 - pow(-2 * x + 2, 3) / 2,
    "out_cubic": lambda x: 1 - pow(1 - x, 3),
}
```

These function have been copied from https://easings.net/ and translated from Javascript to Python. I would like to add the remaining functions to the EASING dict above.

See the animation.py example as a way of testing the above functions.

**Comment by RojerGS** [comment]
I'm having a go at this. Some of the easing functions will look ugly as one-line lambdas. I'll use short `def`s for those and then you'll see how it looks. Does that make sense?

**Comment by willmcgugan** [comment]
Sounds good! Agree re not always using lambda.

**Comment by willmcgugan** [comment]
Can you assign yourself to this? Want to avoid more than one person jumping on a task.

**Comment by RojerGS** [comment]
> 
> 
> Can you assign yourself to this? Want to avoid more than one person jumping on a task.

I can't, probably don't have permission to do that? I think _you_ have to assign me?

**Comment by willmcgugan** [comment]
Ah, I guess I do.

**Comment by tusharsadhwani** [comment]
oh well, I was already done with this one :p

should've messaged first

**Comment by willmcgugan** [comment]
@tusharsadhwani Really? That was quick. Do you want to compare notes with @RojerGS ?

**Comment by tusharsadhwani** [comment]
sure, submitting a patch in 5

**Comment by RojerGS** [comment]
Go ahead and open a PR, I'm currently AFK.

**Comment by willmcgugan** [comment]
No need for a donation! ;-)

**Comment by RojerGS** [comment]
Did _I_ solve your problem? Consider buying _me_ a coffee 🤣

That GH action is a nice addition! To prevent you from adding too many "no donation needed" replies, maybe you'll want to have it _not_ trigger when the issue was opened by you? Just a random thought. Maybe leave it be...

**Comment by willmcgugan** [comment]
I owe you a ☕

**Comment by tusharsadhwani** [comment]
@RojerGS if you don't already have one, you should set up a ko-fi account, it's free and they take no commission.

**Comment by RojerGS** [comment]
I have a Buy Me a Coffee account (associated with my blog) where people can [buy me a slice of pizza](https://buymeacoffee.com/mathspp), maybe I'll move it to ko-fi...

But I do _not_ want Will's coffee for this contribution, and I will refund it if needed 🤣
