### ISSUE TITLE
Mouse codes are printed to the terminal on exit

### ISSUE THREAD

**Issue by willmcgugan** [willmcgugan/textual#82]
Sometimes mouse codes are printed to the terminal on exit. This tends to occur if you are moving the mouse around then exit quickly.

I suspect this is because the app exists prior to all mouse events in stdin being consumed.

Find a way to a) reliably reproduce this error and b) fix it.

I suspect this will require disabling input then posting a null event and waiting for that event to be processed, prior to exiting.

**Comment by lllama** [comment]
I wonder whether [PyAutoGUI](https://github.com/asweigart/pyautogui) could be used as part of this? Have a test wiggle the mouse and then `ctrl-c` the app? Though then you'd have to spawn the app somewhere and then run the test in a separate process/window/etc

**Comment by Tbruno25** [comment]
@willmcgugan I'd like to take a shot at this

**Comment by AcousticCh** [comment]
My programing skills are not intermediate yet but I am a daily linux user. I'd like to try my hand at this, after recreation of the issue I would attempt to turn the unwanted mouse output into a daemon with the subprocess module

**Comment by lllama** [comment]
My thinking is that this would require a shutdown routine for the event loop. In that routine we would use `termios.tcflush()` or similar to flush stdin before we exit. For Windows we would need to use `mscrt` to read keys - not sure if that will translate to mouse events though.

**Comment by willmcgugan** [comment]
Should be fixed in 0.1.13
