### ISSUE TITLE
asyncio event loop isn't closed on exit

### ISSUE THREAD

**Issue by sinus-x** [willmcgugan/textual#9]
When run with Python 3.8.5 on Ubuntu 20.04 LTS, the event loop isn't closed when the example is quit by pressing `q`.

 Following error is output and the program exists:
```
/usr/lib/python3.8/asyncio/base_events:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
```

The terminal is then printing raw bytes (?) of the mouse movement anytime you move the cursor over the window.

![image](https://user-images.githubusercontent.com/14353790/122467790-3d58dd00-cfbb-11eb-9430-45b7a10d18e5.png)

I'm not sure if it's the Python version or some difference between Linux and OSX.

(In order to run the example I had to patch `src/textual/_parser.py`, because the type hint `list[str]` isn't supported in 3.8. I just replaced it with `list`.)

**Comment by willmcgugan** [comment]
Yeah, there is an entire shutdown procedure I need to figure out.

Not sure if you know this, but if your terminal gets messed up like this you can enter "reset" command.

**Comment by sinus-x** [comment]
> you can enter "reset" command.

Yes, I know. I was just wondering if there was a bug on my side -- Textual has nearly 500 stars and no one has filed an issue on this and it isn't mentioned anywhere. I know about the WIP notice in README, but that's rather a vague description.

**Comment by bildzeitung** [comment]
I'm seeing this sort of thing as well.

Further to this, when running the simple example in the source tree, the quit operation takes a very long time (Mac, on iTerm2 or via VS Code).

Observed on the 0.1.8 & master.

**Comment by willmcgugan** [comment]
That’s fixed in a branch I’m working on.

**Comment by bildzeitung** [comment]
Aha! I was about to paste my Python version as well (3.9.6), in case it's some weird asyncio thing ..
